version: '3.9'

services:

  wordpress:
    image: wordpress:php8.0
    restart: always
    init: true
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db
      WORDPRESS_DEBUG: 1
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/themes/korina

  db:
    image: mariadb:10.3
    restart: always
    init: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  wordpress:
